name: Terraform AWS CI/CD

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0   # Adjust the version as needed
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1   # Adjust the region as needed
        
    - name: Initialize Terraform
      run: terraform init
      
    - name: Plan Terraform
      run: terraform plan -out=tfplan
      
    - name: Apply Terraform
      run: terraform apply -auto-approve tfplan
